<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE isys [
	<!ELEMENT isys (info|queries)*>
	<!ELEMENT info (title|version|requirement|directory|revision|release)*>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT version (#PCDATA)>
	<!ELEMENT requirement (revision|version)*>
	<!ELEMENT revision (#PCDATA)>
	<!ELEMENT directory (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT queries (query)*>
	<!ELEMENT query (id|title|check|errmsg|sql)*>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT check (#PCDATA)>
	<!ATTLIST check ident CDATA #REQUIRED>
	<!ELEMENT errmsg (#PCDATA)>
	<!ELEMENT sql (exec)*>
	<!ELEMENT exec (#PCDATA)>
	<!ATTLIST exec ident CDATA #REQUIRED>
	]>
<isys>
	<info>
		<title>Pro</title>
		<version>1.5</version>
		<release>2015-03-09</release>
	</info>
	<queries>
		<query>
			<id>1</id>
			<title></title>
			<check ident="C_VALUE_EXISTS">SELECT isys_language__id FROM isys_language WHERE isys_language__short = 'all'</check>
			<errmsg></errmsg>
			<sql>
				<exec ident="false">
					INSERT INTO `isys_language` VALUES
					 (1,'All','all',0,'ISYS_LANGUAGE_ALL',0);
				</exec>
			</sql>
		</query>
		<query>
			<id>2</id>
			<title></title>
			<check ident="C_VALUE_EXISTS">SELECT isys_language__id FROM isys_language WHERE isys_language__short = 'de'</check>
			<errmsg></errmsg>
			<sql>
				<exec ident="false">
					INSERT INTO `isys_language` VALUES
					 (2,'Deutsch','de',1,'ISYS_LANGUAGE_GERMAN',1);
				</exec>
			</sql>
		</query>
		<query>
			<id>3</id>
			<title></title>
			<check ident="C_VALUE_EXISTS">SELECT isys_language__id FROM isys_language WHERE isys_language__short = 'pt'</check>
			<errmsg></errmsg>
			<sql>
				<exec ident="false">
					INSERT INTO `isys_language` VALUES
					 (4,'Portuguese','pt',1,'ISYS_LANGUAGE_PORTUGUESE',3);
				</exec>
			</sql>
		</query>

	</queries>
</isys>